### ISSUE TITLE
Sending patches upstream?

### ISSUE THREAD

**Issue by petterreinholdtsen** [ROCm/triton#205]
Hi.  Are there plans to submit these changes back to the https://github.com/openai/triton project? I suspect it would be useful for the Debian triton package to only have to consider one code base.

**Comment by nmacchioni** [comment]
@rsanthanam-amd @binarman Tagging for visibility here.

**Comment by zhanglx13** [comment]
@jayfurmanek

**Comment by jayfurmanek** [comment]
Hi all,
Yes, absolutely. It's been delayed a bit because upstream doesn't want a bunch of branched/ifdef'd code to support. The model that's been accepted is a 3rd-party submodule approach.
Upstream recently merged [this](https://github.com/openai/triton/pull/1983) which gives us the submodule link. It currently points to a specific commit that works with the new model, but we'll be reconciling the differences with our latest code from the `triton-mlir` branch. We'll update that submodule link once everything is complete.
